language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
    allow_failures:
        - php: hhvm

services:
  - mongodb

env:
  - SYMFONY_VERSION=2.3.*
  - SYMFONY_VERSION=2.4.*
  - SYMFONY_VERSION=2.5.*

before_script:
  - phpenv config-add travis-php.ini
  - composer require symfony/framework-bundle:${SYMFONY_VERSION} --no-update
  - composer require symfony/validator:${SYMFONY_VERSION} --no-update
  - composer require symfony/finder:${SYMFONY_VERSION} --no-update
  - composer require symfony/doctrine-bridge:${SYMFONY_VERSION} --no-update
  - composer update --dev

script: phpunit
