lexik_translation_list:
    path:     /translations
    defaults: { _controller: "LexikTranslationBundle:Rest:list" }
    methods:  [GET]

lexik_translation_update:
    path:     /translations/{id}
    defaults: { _controller: "LexikTranslationBundle:Rest:update" }
    methods:  [PUT]
